blank_issues_enabled: false
contact_links:
  - name: Discord @greenman999
    url: https://discordapp.com/users/750759710356930591
    about: If you are having issues with usage or have other minor issues, come ask me in my dms!
